STANDARD_DETAILS = {
    "7.G.2": {"label": "Standard 7.G.2", "student_label": "Angle relationships in geometry", "category": "Other"},
    "8.EE.1": {"label": "Standard 8.EE.1", "student_label": "Multiply & divide powers with the same base", "category": "Expressions and Equations"},
    "8.EE.2": {"label": "Standard 8.EE.2", "student_label": "Square & cube roots", "category": "Expressions and Equations"},
    "8.EE.3": {"label": "Standard 8.EE.3", "student_label": "Use scientific notation", "category": "Expressions and Equations"},
    "8.EE.5": {"label": "Standard 8.EE.5", "student_label": "Graph proportional relationships", "category": "Expressions and Equations"},
    "8.EE.6": {"label": "Standard 8.EE.6", "student_label": "Understand slope as rate of change", "category": "Expressions and Equations"},
    "8.EE.7A": {"label": "Standard 8.EE.7A", "student_label": "Solve linear equations (simplify first)", "category": "Expressions and Equations"},
    "8.EE.7B": {"label": "Standard 8.EE.7B", "student_label": "Solve equations with variables on both sides", "category": "Expressions and Equations"},
    "8.EE.8B": {"label": "Standard 8.EE.8B", "student_label": "Solve systems of linear equations", "category": "Expressions and Equations"},
    "8.F.1": {"label": "Standard 8.F.1", "student_label": "Understand functions", "category": "Functions"},
    "8.F.2": {"label": "Standard 8.F.2", "student_label": "Compare functions (graphs, tables, equations)", "category": "Functions"},
    "8.F.3": {"label": "Standard 8.F.3", "student_label": "Identify linear vs. nonlinear", "category": "Functions"},
    "8.F.4": {"label": "Standard 8.F.4", "student_label": "Understand slope & y-intercept from patterns", "category": "Functions"},
    "8.F.5": {"label": "Standard 8.F.5", "student_label": "Describe function behavior from graph", "category": "Functions"},
    "8.G.1": {"label": "Standard 8.G.1", "student_label": "Transformations (translations, rotations, etc.)", "category": "Geometry"},
    "8.G.1A": {"label": "Standard 8.G.1A", "student_label": "Understand rigid motions", "category": "Geometry"},
    "8.G.1B": {"label": "Standard 8.G.1B", "student_label": "Preserve distance & angle with transformations", "category": "Geometry"},
    "8.G.2": {"label": "Standard 8.G.2", "student_label": "Congruent figures with transformations", "category": "Geometry"},
    "8.G.3": {"label": "Standard 8.G.3", "student_label": "Describe the effect of transformations", "category": "Geometry"},
    "8.G.4": {"label": "Standard 8.G.4", "student_label": "Understand similarity using transformations", "category": "Geometry"},
    "8.G.5": {"label": "Standard 8.G.5", "student_label": "Angles in triangles & intersecting lines", "category": "Geometry"},
    "8.G.6": {"label": "Standard 8.G.6", "student_label": "Understand the Pythagorean Theorem", "category": "Geometry"},
    "8.G.7": {"label": "Standard 8.G.7", "student_label": "Apply Pythagorean Theorem to find distances", "category": "Geometry"},
    "8.G.8": {"label": "Standard 8.G.8", "student_label": "Use Pythagorean Theorem in real-world problems", "category": "Geometry"},
    "8.G.9": {"label": "Standard 8.G.9", "student_label": "Volume of cylinders, cones, and spheres", "category": "Geometry"},
    "8.NS.1": {"label": "Standard 8.NS.1", "student_label": "Understand irrational numbers", "category": "The Number System"},
    "8.NS.2": {"label": "Standard 8.NS.2", "student_label": "Estimate square roots and compare irrationals", "category": "The Number System"},
    "8.SP.1": {"label": "Standard 8.SP.1", "student_label": "Construct and interpret scatter plots", "category": "Statistics and Probability"},
    "8.SP.2": {"label": "Standard 8.SP.2", "student_label": "Describe patterns in scatter plots", "category": "Statistics and Probability"},
    "8.SP.3": {"label": "Standard 8.SP.3", "student_label": "Interpret slope and intercepts in context", "category": "Statistics and Probability"},
}