
STANDARD_DETAILS = {
    "7.G.2": {"label": "Standard 7.G.2", "category": "Other"},
    "8.EE.1": {"label": "Standard 8.EE.1", "category": "Expressions and Equations"},
    "8.EE.2": {"label": "Standard 8.EE.2", "category": "Expressions and Equations"},
    "8.EE.3": {"label": "Standard 8.EE.3", "category": "Expressions and Equations"},
    "8.EE.5": {"label": "Standard 8.EE.5", "category": "Expressions and Equations"},
    "8.EE.6": {"label": "Standard 8.EE.6", "category": "Expressions and Equations"},
    "8.EE.7A": {"label": "Standard 8.EE.7A", "category": "Expressions and Equations"},
    "8.EE.7B": {"label": "Standard 8.EE.7B", "category": "Expressions and Equations"},
    "8.EE.8B": {"label": "Standard 8.EE.8B", "category": "Expressions and Equations"},
    "8.F.1": {"label": "Standard 8.F.1", "category": "Functions"},
    "8.F.2": {"label": "Standard 8.F.2", "category": "Functions"},
    "8.F.3": {"label": "Standard 8.F.3", "category": "Functions"},
    "8.F.4": {"label": "Standard 8.F.4", "category": "Functions"},
    "8.F.5": {"label": "Standard 8.F.5", "category": "Functions"},
    "8.G.1": {"label": "Standard 8.G.1", "category": "Geometry"},
    "8.G.1A": {"label": "Standard 8.G.1A", "category": "Geometry"},
    "8.G.1B": {"label": "Standard 8.G.1B", "category": "Geometry"},
    "8.G.2": {"label": "Standard 8.G.2", "category": "Geometry"},
    "8.G.3": {"label": "Standard 8.G.3", "category": "Geometry"},
    "8.G.4": {"label": "Standard 8.G.4", "category": "Geometry"},
    "8.G.5": {"label": "Standard 8.G.5", "category": "Geometry"},
    "8.G.6": {"label": "Standard 8.G.6", "category": "Geometry"},
    "8.G.7": {"label": "Standard 8.G.7", "category": "Geometry"},
    "8.G.8": {"label": "Standard 8.G.8", "category": "Geometry"},
    "8.G.9": {"label": "Standard 8.G.9", "category": "Geometry"},
    "8.NS.1": {"label": "Standard 8.NS.1", "category": "The Number System"},
    "8.NS.2": {"label": "Standard 8.NS.2", "category": "The Number System"},
    "8.SP.1": {"label": "Standard 8.SP.1", "category": "Statistics and Probability"},
    "8.SP.2": {"label": "Standard 8.SP.2", "category": "Statistics and Probability"},
    "8.SP.3": {"label": "Standard 8.SP.3", "category": "Statistics and Probability"},
}